# Generated by Django 4.2.4 on 2023-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_inscripcion_usuario_codigo_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
